# Based on blog post https://medium.freecodecamp.org/how-to-stop-errors-before-they-ever-hit-your-codebase-with-travis-ci-and-eslint-7a5a6b1fcd4a

language: node_js

node_js:
  - 'node' # Check against the latest stable Node release, currently: 11.x
  - 'lts/*' # Check against the active long-term support (LTS), currently: 10.x
  - '11' # Current release
  - '10' # Active LTS until April 2020 (according to https://github.com/nodejs/Release)
  - '8' # Maintenance LTS until December 2019
  - '6' # Maintenance LTS until April 2019

before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

cache:
  directories:
    - node_modules

sudo: false
