#!/usr/vin/env node

/*
 * validate-trees.js validates the trees generated by generate-tests.js by testing
 * three things:
 *  - 1. Whether we have the correct numbers of bifurcating and multifurcating trees.
 *  - 2. Whether all trees generated are distinct from each other.
 *  - 3. Whether all bifurcating trees are identical to those generated by COMPONENT.
 *       (see the `from-component` directory).
 */

const fs = require('fs');
const path = require('path');

const treeDirs = fs.readdirSync(".").filter(fn => fn.toLowerCase().match(/^n\d+/));
const treeFiles = treeDirs.map(fn => path.join(fn, "trees.nex"));

// We're not going to actually try to fully parse the Newick files; instead,
// we will look for `TREE ...` lines.
treeFiles.forEach(treeFile => {
  const content = fs.readFileSync(treeFile, encoding='utf8');
  for (const match of content.matchAll(/^\s*TREE \w+ = (.*);\s*/mg)) {
    const tree = match[1];
    console.log(`In ${treeFile} found tree: ${tree}`);
  }
});
