# This workflow will test this Node.js package.
# For more information see: https://docs.github.com/en/actions/guides/building-and-testing-nodejs

name: Build and Test

# Execute on every push, pull request and if activated manually.
on: [push, pull_request, workflow_dispatch]

# The caching settings were based on https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Clean install dependencies from package-lock.json.
      run: npm ci

    - name: Build with NPM
      run: npm run build --if-present

    - name: Test with NPM
      run: npm test
